apiVersion: apps/v1
kind: Deployment
metadata:
  name: charts
  labels:
    app: charts
spec:
  replicas: "{{$.iios.app.replicas}}"
  selector:
    matchLabels:
      app: charts
  template:
    metadata:
      labels:
        app: charts
    spec:
      containers:
      - name: charts
        image: "ignitial/charts:{{$.iios.app.version}}"
        imagePullPolicy: "{{$.iios.app.imagePullPolicy}}"
        volumeMounts:
        - name: config-volume
          mountPath: /opt/charts/server/config/generated
        ports: "{{$.iios.app.ports}}"
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: config-volume
          configMap:
            name: charts-config

---
apiVersion: v1
kind: Service
metadata:
  name: charts
spec:
  selector:
    app: charts
  ports:
  - name: http
    port: "{{$.iios.app.ports[0].containerPort}}"
    targetPort: "{{$.iios.app.ports[0].containerPort}}"
